### ISSUE TITLE
Schema problem with EventProduct

### ISSUE THREAD

**Issue by mrjrdg** [mrjrdg/marque-sans-nom#10]
### Context

At the last meeting, we discuss the idea of a class that would be an `EventProduct`  (A event created by a `Business` that represent an event that an `ApplicationUser` could rent).

### Problem

The problem with that that we didn't think of is that our current relation model would need a lot of modification (It's my fault i didn't think of some problems when i created the model).

### What i propose

I propose that when a `Business` create an `Event X`, That same `Event X` would have at the begining the owner set to null in the database. When a user rent the `Event X`, we would then set the owner to that `ApplicationUser`.

**Comment by phsoucy** [comment]
De ce que je comprends, c’est mieux comme ça puisque ça règle en même tant le problème por les disponibilité.

Ainsi, corrigé moi si je me trompe, une entreprise pourrait créer « une plage horaire » où l’event avec le lieux est disponible pour louer disons le lundi soir, et on pourrait louer cette plage horaire.

Philippe Soucy
________________________________
De : mrjrdg <notifications@github.com>
Envoyé : Sunday, February 16, 2020 5:17:08 PM
À : mrjrdg/marque-sans-nom <marque-sans-nom@noreply.github.com>
Cc : Subscribed <subscribed@noreply.github.com>
Objet : [mrjrdg/marque-sans-nom] Event Issue (#10)

Context

At the last meeting, we discuss the idea of a class that would be an EventProduct (A event created by a Business that represent an event that an ApplicationUser could rent).

Problem

The problem with that that we didn't think of is that our current relation model do not would need a lot of modification (It's my fault i didn't think of some problem when i create the model).

What i propose

I propose that when a Business create an Event X, That same event X would have at the begining the owner set to null in the database. When a user rent it, we would then set the owner to that ApplicationUser.

**Comment by mrjrdg** [comment]
En fais va voir mon schema dans l'issue #2 . Quand une `Business` va creer un `Event`, cette meme `Event` va au debut avoir le champ `ApplicationUser` a null. C'est ce qui va definir si un evenement est disponible ou non. 

(Note : Dans le schema je parle de la table `Event` et plus specifiquement du champs FK ApplicationUser (qui en fais devrait etre ApplicationUserId))

**Comment by lecanardcolvert** [comment]
>  C'est ce qui va definir si un evenement est disponible ou non.

Que veux-tu dire par "disponible" ?

**Comment by phsoucy** [comment]
Parce que on avait le problème de gérer les cas où une salle par exemple était déjà loué à l'interne par exemple.

**Comment by mrjrdg** [comment]
1. La `Business Y` creer un `Event X`.
2. L'`ApplicationUserID` de `X` est a null car elle n'est pas encore loue.
3. L'`ApplicationUser Z` loue `X`.
4. l'`ApplicationUserId` de `X` sera maintenant la valeur de l'`Id` de `Z`

Donc si un `Event` n'a pas de proprietaire `customer` ca veu dire quelle n'est pas loue.

**Comment by lecanardcolvert** [comment]
Pourquoi ne pas créer une table `Participant` pour faire le lien entre `Event` et `User` ?

**Comment by mrjrdg** [comment]
C'est deja fait ca la on parle du user qui va louer l'evenement a la business

**Comment by lecanardcolvert** [comment]
Ok je comprends cela. Qu'est-ce qui différencie le premier User qui s'inscrit à l'événement vs les autres ? Ce sera lui l'organisateur ?

**Comment by mrjrdg** [comment]
Non au depart les evenements sont listés puis un membre loue un evenement. Ensuite l'evenement lui est deleguer

**Comment by mrjrdg** [comment]
ensuite les autres membres peuvent se joindre a l'evenement

**Comment by lecanardcolvert** [comment]
Je crois que c'est les termes utilisés qui sont mélangeants pour moi. Pouvez-vous svp me rafraîchir la mémoire un peu.

L'entreprise offre par exemple des terrains, des gymnases, des salles, etc. Un utilisateur (n'importe qui) peut "réserver" des installations et y organiser un événement. D'autres utilisateurs peuvent se joindre aux événements.

Est-ce bien ça ?

**Comment by lecanardcolvert** [comment]
Je pense que c'est ça le concept si je me base sur le contrat. Dans ce cas il faudrait utiliser un terme comme "ressource / endroit / lieu" pour désigner ce qui est offert par l'entreprise.

Donc :
1. L'entreprise crée une ressource. Ex. "Gymnase"
2. L'entreprise assigne des disponibilités à la ressource. Ex. "disponible le lundi de 18h à 21h"
3. L'utilisateur crée un événement en utilisant une ressource disponible. La ressource est maintenant indisponible.

Il faut penser à comment va se faire le lien `ressource + disponibilité + user qui réserve la ressource`  en tenant compte du fait qu'une entreprise ne devrait pas à devoir créer deux fiches de ressources pour un même endroit à deux disponibilités différentes.

D'ailleurs il faudra gérer un scénario où une entreprise décide de rendre indisponible une ressource lorsqu'il y a déjà un événement de prévu.

Finalement, quoi faire s'il n'y a aucune ressource ? Est-ce que cela veut dire que personne ne peut créer d'événements ?

**Comment by sheik2306** [comment]
Moi je laisserais faire la notion d'entreprise pour comprendre. Ont offre une evenement a une certaine endroit qui offre ce service. L'utilisateur a la possibilite de reserver le lieux pour une certaine heure et date. Disponible en tout temps. Le seul conflit de location est quand nos utilisateurs book de 2h30 a 3h30, bien un autre utilisateur ne pourra pas booker de 2h30 a 3h30 pour ce meme lieux, c'est pas l'entreprise qui va decider que c'est indisponible c'est notre horaire de temps selon les utilisateur

**Comment by lecanardcolvert** [comment]
> Ont offre une evenement a une certaine endroit qui offre ce service.

Qui "on" ?

> c'est pas l'entreprise qui va decider que c'est indisponible c'est notre horaire de temps selon les utilisateur

Il doit absolument y avoir un endroit où une entreprise spécifie la disponibilité d'un lieu pour plusieurs raisons (ex. congé, autre activité en dehors de la plateforme, heures d'ouverture / fermeture).

Pourriez-vous me valider un des scénarios afin que je comprenne votre idée car, pour moi, il n'y a rien de clair et précis.

**Scénario 1**
- L'entreprise crée un endroit : _Gymnase_
- L'entreprise crée un événement. Elle doit choisir l'endroit et l'heure car elle est la seule à connaître à quel moment l'endroit en question est disponible. Donc elle crée : _Soccer au gymnase, lundi de 18h à 21h_
- L'utilisateur s'inscrit à cet événement

**Scénario 2**
- L'entreprise crée un endroit et lui assigne des heures de disponibilité car elle est la seule à savoir à quel moment l'endroit est disponible. Donc elle crée : _Gymnase (disponibilités : lundi au vendredi, de 18h à 21h)_
- L'entreprise crée un "événement potentiel". Elle doit choisir le lieu et n'assigne aucune heure. Donc elle crée : _Soccer au gymnase (ce lieu est disponible lundi au vendredi, de 18h à 21h)_
- L'utilisateur est intéressé par "l'événement potentiel" de l'entreprise. Il décide à quel moment l'événement doit avoir lieu. Donc il crée : _Soccer au gymnase, lundi de 18h à 21h (car le lieu est disponible à ces heures)_

Si ce n'est pas un de ces scénarios, veuillez svp me l'expliquer clairement.
