### ISSUE TITLE
UserList du script DataTables ne s'affiche pas bien

### ISSUE THREAD

**Issue by sheik2306** [mrjrdg/marque-sans-nom#18]
@lecanardcolvert 
@sheik2306 
Soit le fichier Views/Event/userList.cshtml ne s'affiche pas comme :
 le fichier statique dans wwwroot/user-list.html

Probleme d'integration du fichier datatables (script)

**Comment by lecanardcolvert** [comment]
Le problème est résolu. Aussi, le DataTable s'affiche maintenant en français.
