### ISSUE TITLE
Gestion des événements

### ISSUE THREAD

**Issue by lecanardcolvert** [mrjrdg/marque-sans-nom#21]

**Comment by sheik2306** [comment]
@lecanardcolvert manque seulement a mieux afficher l'index des evenements pour l'instant
rechercher un evenement n'est pas encore disponible

**Comment by lecanardcolvert** [comment]
J'ai corrigé le problème d'affichage pour la liste des événements.

Nous pourrons ouvrir un autre billet spécifiquement pour la recherche d'événements plus tard car "gestion des événements" c'est trop large.
