### ISSUE TITLE
Liste des entreprises (backend)

### ISSUE THREAD

**Issue by lecanardcolvert** [mrjrdg/marque-sans-nom#24]
Cette page : 
https://localhost:44336/Business

Veuillez svp vous assurer que tous les éléments de l'adresse y sont.
Le bouton Edit ne fonctionne pas.
Le bouton Delete ne fonctionne pas.

**Comment by sheik2306** [comment]
"Veuillez svp vous assurer que tous les éléments de l'adresse y sont." Front end, voir @Html.Displayfor Business.Address."x"

**Comment by lecanardcolvert** [comment]
@sheik2306 
Tu as raison.

@phsoucy 
Pourrais-tu t'occuper de mettre tous les éléments et d'ajuster le visuel ?
Si tu veux pour l'action Delete par exemple tu peux utiliser des icônes de FontAwesome : 
https://fontawesome.com/icons?d=gallery
