### ISSUE TITLE
Modifier une entreprise (backend)

### ISSUE THREAD

**Issue by lecanardcolvert** [mrjrdg/marque-sans-nom#28]
Cette page :
https://localhost:44336/Business/Edit/1

Elle ne fonctionne pas. J'ai une page d'erreur. 

Il faut s'assurer qu'elle fonctionne.

**Comment by sheik2306** [comment]
Je vais faire un delete et add, pas de edit alors

**Comment by sheik2306** [comment]
Edit Entreprise fonctionne
