### ISSUE TITLE
Supprimer une entreprise (backend)

### ISSUE THREAD

**Issue by lecanardcolvert** [mrjrdg/marque-sans-nom#30]
Cette page :
https://localhost:44336/Business/Delete/1

Elle ne fonctionne pas. Il faudrait qu'elle fonctionne.

Est-ce que cette page doit afficher quelque chose du genre "Voulez-vous supprimer l'entreprise X ?" ou elle fait seulement l'action de supprimer, puis redirige vers la liste des entreprises ?

**Comment by sheik2306** [comment]
Supression d'une entreprise fonctionne
