### ISSUE TITLE
Afficher un événement (backend)

### ISSUE THREAD

**Issue by lecanardcolvert** [mrjrdg/marque-sans-nom#31]
Cette page :
https://localhost:44336/Event/1

Il faut afficher les utilisateurs inscrits à l'événement et toutes les autres informations nécessaires.

**Comment by sheik2306** [comment]
Tu peux apprendre a faire un @html.Displayfor model.user et tu va avoir ton utilisateur.... ca fais partie du front end , tu as tout ce qu'il faut avec le model qu'il te retourne sur la page
