### ISSUE TITLE
Créer un événement (backend)

### ISSUE THREAD

**Issue by lecanardcolvert** [mrjrdg/marque-sans-nom#33]
Cette page : 
https://localhost:44336/Event/CreateEvent?area=Identity

Pouvez-vous ajouter un champ Description qui doit pouvoir contenir beaucoup de caractères.
Il faudrait aussi pouvoir téléverser une image qui représente l'événement.

**Comment by sheik2306** [comment]
Bonne observation pour le televersement de fichier. Tu peux proceder a apprendre comment, je suis deja occuper sur les fonctionalites de modifier les entreprises, modifier evenement, supprimer evenement et supprimer entreprises.

**Comment by lecanardcolvert** [comment]
Depuis la dernière màj, j'ai un message d'erreur lorsque je tente d'afficher un événement que j'ai créé avec ce formulaire : 

https://localhost:44336/Event/CreateEvent?area=Identity

**Comment by mrjrdg** [comment]
Moi ca fonctionne je vien de tester il faudrais plus d'informations

Etapes 

1.  Je suis aller sur https://localhost:5001/Event/CreateEvent?area=Identity
2. j'ai rempli chaque champ et j'ai creer l'evenement
3. j'ai cliquer sur le nouvel evenement creer qui maintenant s'affiche sur la page d'accueil

**Comment by lecanardcolvert** [comment]
Le problème est que je peux afficher `@Model.Event.ApplicationUser.FirstName` seulement pour les 2 premiers événements (data seeding) mais pas pour les nouveaux événements créés avec le formulaire.

**Comment by mrjrdg** [comment]
De quelle url parles-tu ? Parce que je ne te suit pas.

**Comment by sheik2306** [comment]
C'est parceque au debut il ne sont pas des "Members" de l'evenement

**Comment by lecanardcolvert** [comment]
Dans la page Event.cshtml, j'aimerais afficher l'organisateur de l'événement. C'est celui qui crée l'événement non ?

Dans Event.cs, il y a : 
```
        /// <summary>
        ///     The owner ApplicationUser of this event
        /// </summary>
        /// <value></value>
        public ApplicationUser ApplicationUser { get; set; }
```

Est-ce que cela correspond à l'utilisateur qui crée l'événement ?

Si oui alors `@Model.Event.ApplicationUser.FirstName` devrait fonctionner dans la page Event.cshtml à moins que je ne me trompe.

Étrangement ça fonctionne seulement pour les 2 events qui sont créés par le data-seeding.

**Comment by lecanardcolvert** [comment]
OK pour ce billet, voici ce qu'il reste à faire :

- Lors de la création d'événement, il faudrait assigner un `ApplicationUser.id` au lieu d'un objet `ApplicationUser` (je pourrais juste inclure un hidden input `ApplicationUser.id` dans le frontend) ? 
Ou sinon assigner l'objet `ApplicationUser `directement dans la fonction CreateEvent ?
- Lors de la création d'événement, il faut ajouter le ApplicationUser à la Event.Members
- Téléversement d'une image qui représente l'événement
- Une fois qu'un événement est créé, il faut afficher l'événement au lieu de retourner à l'index
- Lors de la création d'événement, il faut créer un nouveau objet MessageBoard et assigner à Event

**Comment by sheik2306** [comment]
Televersement sera dans un autre ticket, et non pour ajouter ApplicationUser a Event.Members, fais juste ajouter ApplicationUser a liste des membres participants dans l'HTML, c'est la seule maniere de differencier le createur d'evenement et les participants

**Comment by lecanardcolvert** [comment]
Ce bug est toujours là : 
https://github.com/mrjrdg/marque-sans-nom/issues/33#issuecomment-609506209

Voici l'erreur que j'obtiens lorsque je tente d'afficher @Model.Event.ApplicationUser.FirstName : 

> System.NullReferenceException
>   HResult=0x80004003
>   Message=Object reference not set to an instance of an object.
>   Source=webapp.Views
>   Arborescence des appels de procédure :
>    at AspNetCore.Views_Event_Event.<ExecuteAsync>d__38.MoveNext() in C:\Users\alxbo\Source\Repos\mrjrdg\marque-sans-nom\webapp\Views\Event\Event.cshtml:line 30

Aussi, lorsque l'événement est créé, pouvez-vous faire en sorte d'afficher le nouvel événement au lieu de retourner à l'index ?

**Comment by phsoucy** [comment]
Je confirme que lorsque je crée un événement et que je tente de l'afficher, j'ai la même erreur. J'ai du seedé la database hier pour faire des tests car on ne peut pas en local.

**Comment by sheik2306** [comment]
C'est regler, 

mais il y'a un probleme de date Picker, le format n'est pas le bon avec datepicker ca n'enregistre pas le bon temps. Quand nous l'ecrivons normalement ca fonctionne. Si nous avons le temps d'arranger le date picker sinon enlever et ecrire a main.
