### ISSUE TITLE
Rejoindre un événement (backend)

### ISSUE THREAD

**Issue by lecanardcolvert** [mrjrdg/marque-sans-nom#40]
Cette page : 
https://localhost:44336/Event/1

Un utilisateur doit pouvoir s'inscrire à un événement s'il n'est pas dans la liste des participants.
Un utilisateur doit pouvoir se désinscrire à un événement s'il est dans la liste des participants ET que l'événement n'est pas terminé.

Une fois que c'est fait, je vais ajuster le frontend en conséquence (afficher les boutons). Voir #32

**Comment by lecanardcolvert** [comment]
Pouvez-vous svp me dire comment je peux faire pour récupérer l'objet ApplicationUser de l'utilisateur qui est connecté ?

**Comment by lecanardcolvert** [comment]
La partie Rejoindre un événement est faite, il ne reste plus que la désinscription.

**Comment by sheik2306** [comment]
C'est fait.
