### ISSUE TITLE
Supprimer un événement (backend)

### ISSUE THREAD

**Issue by lecanardcolvert** [mrjrdg/marque-sans-nom#46]
Cette page :
https://localhost:44336/Event/Delete/1

Il faut créer le backend qui permet la suppression d'un événement (pas obligé de supprimer l'image).

Normalement il ne faudrait pas pouvoir supprimer un événement qui est passé (date/heure aujourd'hui vs Event.EndDate).

Lorsque l'événement a été supprimé, il faudrait revenir à la page qui affichera les événements de l'utilisateur. (si on voulait bien faire, si c'est un utilisateur qui supprime son événement alors il y aurait une redirection vers la liste de ses événements, et si c'est un administrateur qui supprime un événement, alors il y aurait une redirection vers la liste globale des événements...)

**Comment by phsoucy** [comment]
J'ai besoin que cette issue soit terminé pour pouvoir faire #47

**Comment by phsoucy** [comment]
Ça semble fonctionner quand on clique sur supprimer.
