### ISSUE TITLE
Supprimer un événement (frontend)

### ISSUE THREAD

**Issue by lecanardcolvert** [mrjrdg/marque-sans-nom#47]
Cette page :
https://localhost:44336/Event/Delete/1

Phil va s'assurer que ça s'affiche bien.

**Comment by phsoucy** [comment]
Je ne comprends pas pourquoi créer une page spécifique pour ça. Quand on clique sur supprimer ça semble fonctionner. Voir #46

**Comment by lecanardcolvert** [comment]
Le problème est que le backend n'est pas cohérent.

Par exemple : 

Lorsqu'on supprime une entreprise, il y a une page de confirmation comme celle-ci :
https://localhost:44336/Business/Delete/1

Lorsqu'on supprime un rôle, il n'y a pas de page de confirmation.

Maintenant, lorsqu'on supprime un événement, il n'y a pas de page de confirmation non plus. J'avais demandé à ce que ce soit fait dans le billet #46 mais au final ça n'a pas été fait.

Selon moi, c'est toujours mieux d'avoir une page de confirmation car, en entreprise, ça peut arriver qu'on clique sur quelque chose par erreur et qu'on ait besoin de revenir en arrière. Selon moi, c'est important d'être constant dans le design pour aider à ce que ce soit plus intuitif.

Pour ce billet je dirais que la seule chose à améliorer compte tenu des circonstances est le placement des boutons Supprimer / Éditer dans la page. Moi j'aime placer ces boutons en haut.

Tu peux te baser sur cette page, c'est assez simple : 
https://localhost:44336/Business/1

**Comment by phsoucy** [comment]
J'ai fait comme demandé et j'ai ajouté une demande de confirmation en collapsible
