### ISSUE TITLE
Afficher une entreprise (backend)

### ISSUE THREAD

**Issue by lecanardcolvert** [mrjrdg/marque-sans-nom#56]
Cette page : 
https://localhost:44336/Business/1

Il faut qu'elle fonctionne.

Parmi les informations qui seront affichées : 
- Le nom
- L'adresse
- Les événements liés à cette entreprise
- Les services offerts (champ String)

**Comment by sheik2306** [comment]
L'affichage de UN entreprise est fait, voir : Liste D'entreprise et cliquer sur une entreprise pour y acceder
