### ISSUE TITLE
Rechercher un événement (backend)

### ISSUE THREAD

**Issue by lecanardcolvert** [mrjrdg/marque-sans-nom#58]
Il faut créer une fonction qui prend en paramètre un mot-clé et qui va :

- Créer une liste des événements actifs (`Now < Event.StartDate`)
- Rechercher le mot-clé dans titre, description, business.name, adresse, catégorie, dans chaque événement
- Retourner la liste des événements qui correspondent

**Comment by sheik2306** [comment]
Recherche par titre et Event type terminer, peux ajouter d'autres plus tards si nous avons le temps
