### ISSUE TITLE
Historique d'événements (backend)

### ISSUE THREAD

**Issue by lecanardcolvert** [mrjrdg/marque-sans-nom#60]
Il faut créer une page qui va permettre d'afficher une liste de tous les événements pour lesquels le ApplicationUser connecté était participant (`Event.Membres`).

**Comment by sheik2306** [comment]
Terminer

**Comment by lecanardcolvert** [comment]
Pouvez-vous créer une page qui va servir à afficher seulement les événements de l'utilisateur (passés et futur) ?

**Comment by sheik2306** [comment]
Moi je ferais tout dans ton Index, tu as deja le model qu'il faut avec le temps qu'il reste ca sera le plus simple

```
1.
<h1> Les evenements complets
if user not in members ou application user alors afficher les events 


2. Afficher ses evenements ( deja fais )
<h1>Ma Liste d'evenement:<h1>
@if ( oneEvent.Member == user || oneEvent.ApplicationUser == user )
Events,
blablalba

3.
<h1>Mon historique:<h1>
Deja fais.
```
