### ISSUE TITLE
Historique d'événements (frontend)

### ISSUE THREAD

**Issue by lecanardcolvert** [mrjrdg/marque-sans-nom#61]
Il faudra afficher cette page un peu de la même façon que celle-ci : 
https://localhost:44336/Event

**Comment by phsoucy** [comment]
Je ne comprends pas ce billet, c'est déjà le cas... Il faut cependant être inscrit à au moins un événement passé pour qu'il s'affiche sur cette page...
@lecanardcolvert

**Comment by lecanardcolvert** [comment]
En fait ce billet est en lien avec une page qui n'existe pas encore mais qui devrait exister : l'historique des événements de l'utilisateur qui est connecté.

**Comment by phsoucy** [comment]
Oui mais cela s'affiche déjà en dessous de la liste des événements de la page `/Event`

**Comment by lecanardcolvert** [comment]
En fait la section "Événement passés" affiche tous les événements dans le passé.

Il nous faut une page où l'utilisateur peut voir seulement tous les événements auxquels il va participer / a déjà participé.

**Comment by phsoucy** [comment]
Donc cette issue est dépendante aussi de #60

**Comment by sheik2306** [comment]
J'ai fermer l'issue #60 ,je ne vois pas le probleme a ajouter une section dans Index :
Evenement non-participant
le model a deja tout ce qu'il faut pour afficher les evenements 

https://github.com/mrjrdg/marque-sans-nom/issues/60#issuecomment-613645811

**Comment by sheik2306** [comment]
Modifier un peu le style de chaque section a defaut de

**Comment by phsoucy** [comment]
J'ai fait comme : https://github.com/mrjrdg/marque-sans-nom/issues/60#issuecomment-613645811
et j'ai résolu un bug avec la variable `isInEvent` qui ne considérait si le current user participait au premier événement de la liste à chaque tour de boucle.
